// ============================================
// LANGUAGE STORE
// Manages website language and translations
// Supports 15 languages with flag emojis
// ============================================

import { create } from 'zustand';
import { persist } from 'zustand/middleware';

// ============================================
// SUPPORTED LANGUAGES
// ============================================
export type LanguageCode = 
  | 'en' | 'zh' | 'hi' | 'es' | 'fr' | 'ar' | 'bn' | 'pt' 
  | 'ru' | 'nl' | 'ur' | 'id' | 'de' | 'ja' | 'pcm' | 'mr';

export interface Language {
  code: LanguageCode;
  name: string;
  nativeName: string;
  flag: string;
  dir: 'ltr' | 'rtl';
}

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧', dir: 'ltr' },
  { code: 'zh', name: 'Mandarin Chinese', nativeName: '中文', flag: '🇨🇳', dir: 'ltr' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳', dir: 'ltr' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸', dir: 'ltr' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷', dir: 'ltr' },
  { code: 'ar', name: 'Modern Standard Arabic', nativeName: 'العربية', flag: '🇸🇦', dir: 'rtl' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇧🇩', dir: 'ltr' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹', dir: 'ltr' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺', dir: 'ltr' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', flag: '🇳🇱', dir: 'ltr' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', flag: '🇵🇰', dir: 'rtl' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩', dir: 'ltr' },
  { code: 'de', name: 'Standard German', nativeName: 'Deutsch', flag: '🇩🇪', dir: 'ltr' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵', dir: 'ltr' },
  { code: 'pcm', name: 'Nigerian Pidgin', nativeName: 'Naija', flag: '🇳🇬', dir: 'ltr' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳', dir: 'ltr' },
];

export const getLanguageByCode = (code: LanguageCode): Language => {
  return SUPPORTED_LANGUAGES.find(l => l.code === code) || SUPPORTED_LANGUAGES[0];
};

// ============================================
// TRANSLATIONS
// ============================================
export type TranslationKey = 
  // Navigation
  | 'nav.home' | 'nav.forum' | 'nav.members' | 'nav.messages' | 'nav.blog' | 'nav.game' | 'nav.search'
  | 'nav.login' | 'nav.register' | 'nav.logout' | 'nav.profile' | 'nav.settings' | 'nav.admin'
  // Common
  | 'common.loading' | 'common.error' | 'common.success' | 'common.cancel' | 'common.save'
  | 'common.delete' | 'common.edit' | 'common.create' | 'common.search' | 'common.filter'
  | 'common.sort' | 'common.newest' | 'common.oldest' | 'common.hot' | 'common.all'
  // Forum
  | 'forum.threads' | 'forum.posts' | 'forum.comments' | 'forum.replies' | 'forum.views'
  | 'forum.lastPost' | 'forum.noThreads' | 'forum.createThread' | 'forum.reply'
  | 'forum.subforums' | 'forum.searchPlaceholder'
  // Auth
  | 'auth.username' | 'auth.password' | 'auth.email' | 'auth.phone' | 'auth.confirmPassword'
  | 'auth.loginTitle' | 'auth.registerTitle' | 'auth.forgotPassword' | 'auth.rememberMe'
  | 'auth.noAccount' | 'auth.haveAccount' | 'auth.signUp' | 'auth.signIn'
  | 'auth.country' | 'auth.language' | 'auth.selectCountry' | 'auth.selectLanguage'
  // Profile
  | 'profile.motto' | 'profile.posts' | 'profile.comments' | 'profile.joined'
  | 'profile.editProfile' | 'profile.sendMessage' | 'profile.activity'
  | 'profile.updates' | 'profile.settings'
  // Messages
  | 'messages.inbox' | 'messages.sent' | 'messages.compose' | 'messages.subject'
  | 'messages.content' | 'messages.send' | 'messages.noMessages'
  // Blog
  | 'blog.latest' | 'blog.readMore' | 'blog.author' | 'blog.published'
  | 'blog.related' | 'blog.minRead' | 'blog.backToBlog'
  // Game
  | 'game.play' | 'game.score' | 'game.highScore' | 'game.leaderboard'
  | 'game.start' | 'game.gameOver' | 'game.restart'
  // SEO
  | 'seo.siteTitle' | 'seo.siteDescription' | 'seo.forumTitle' | 'seo.blogTitle';

const translations: Record<LanguageCode, Partial<Record<TranslationKey, string>>> = {
  // English (default)
  en: {
    'nav.home': 'Home',
    'nav.forum': 'Forum',
    'nav.members': 'Members',
    'nav.messages': 'Messages',
    'nav.blog': 'Blog',
    'nav.game': 'Flappy Watch',
    'nav.search': 'Search',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.logout': 'Logout',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.admin': 'Admin',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.newest': 'Newest',
    'common.oldest': 'Oldest',
    'common.hot': 'Hot',
    'common.all': 'All',
    'forum.threads': 'Threads',
    'forum.posts': 'Posts',
    'forum.comments': 'Comments',
    'forum.replies': 'Replies',
    'forum.views': 'Views',
    'forum.lastPost': 'Last Post',
    'forum.noThreads': 'No threads yet',
    'forum.createThread': 'Create Thread',
    'forum.reply': 'Reply',
    'forum.subforums': 'Sub-forums',
    'forum.searchPlaceholder': 'Search threads...',
    'auth.username': 'Username',
    'auth.password': 'Password',
    'auth.email': 'Email',
    'auth.phone': 'Phone Number',
    'auth.confirmPassword': 'Confirm Password',
    'auth.loginTitle': 'Sign In',
    'auth.registerTitle': 'Create Account',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.rememberMe': 'Remember Me',
    'auth.noAccount': "Don't have an account?",
    'auth.haveAccount': 'Already have an account?',
    'auth.signUp': 'Sign Up',
    'auth.signIn': 'Sign In',
    'auth.country': 'Country',
    'auth.language': 'Language',
    'auth.selectCountry': 'Select your country',
    'auth.selectLanguage': 'Select your language',
    'profile.motto': 'Motto',
    'profile.posts': 'Posts',
    'profile.comments': 'Comments',
    'profile.joined': 'Joined',
    'profile.editProfile': 'Edit Profile',
    'profile.sendMessage': 'Send Message',
    'profile.activity': 'Activity',
    'profile.updates': 'Updates',
    'profile.settings': 'Settings',
    'messages.inbox': 'Inbox',
    'messages.sent': 'Sent',
    'messages.compose': 'Compose',
    'messages.subject': 'Subject',
    'messages.content': 'Message',
    'messages.send': 'Send',
    'messages.noMessages': 'No messages',
    'blog.latest': 'Latest Articles',
    'blog.readMore': 'Read More',
    'blog.author': 'Author',
    'blog.published': 'Published',
    'blog.related': 'Related Articles',
    'blog.minRead': 'min read',
    'blog.backToBlog': 'Back to Blog',
    'game.play': 'Play',
    'game.score': 'Score',
    'game.highScore': 'High Score',
    'game.leaderboard': 'Leaderboard',
    'game.start': 'Start Game',
    'game.gameOver': 'Game Over',
    'game.restart': 'Play Again',
    'seo.siteTitle': 'Watch Trading Forums',
    'seo.siteDescription': 'The premier community for watch traders and collectors worldwide',
    'seo.forumTitle': 'Watch Trading Forum',
    'seo.blogTitle': 'Watch Trading Blog',
  },
  // Mandarin Chinese
  zh: {
    'nav.home': '首页',
    'nav.forum': '论坛',
    'nav.members': '会员',
    'nav.messages': '消息',
    'nav.blog': '博客',
    'nav.game': '游戏',
    'nav.search': '搜索',
    'nav.login': '登录',
    'nav.register': '注册',
    'nav.logout': '退出',
    'nav.profile': '个人资料',
    'nav.settings': '设置',
    'nav.admin': '管理',
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.cancel': '取消',
    'common.save': '保存',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.create': '创建',
    'common.search': '搜索',
    'common.filter': '筛选',
    'common.sort': '排序',
    'common.newest': '最新',
    'common.oldest': '最早',
    'common.hot': '热门',
    'common.all': '全部',
    'forum.threads': '主题',
    'forum.posts': '帖子',
    'forum.comments': '评论',
    'forum.replies': '回复',
    'forum.views': '浏览',
    'forum.lastPost': '最后回复',
    'forum.noThreads': '暂无主题',
    'forum.createThread': '发布主题',
    'forum.reply': '回复',
    'forum.subforums': '子论坛',
    'forum.searchPlaceholder': '搜索主题...',
    'auth.username': '用户名',
    'auth.password': '密码',
    'auth.email': '邮箱',
    'auth.phone': '电话号码',
    'auth.confirmPassword': '确认密码',
    'auth.loginTitle': '登录',
    'auth.registerTitle': '创建账户',
    'auth.forgotPassword': '忘记密码？',
    'auth.rememberMe': '记住我',
    'auth.noAccount': '还没有账户？',
    'auth.haveAccount': '已有账户？',
    'auth.signUp': '注册',
    'auth.signIn': '登录',
    'auth.country': '国家',
    'auth.language': '语言',
    'auth.selectCountry': '选择您的国家',
    'auth.selectLanguage': '选择您的语言',
    'profile.motto': '座右铭',
    'profile.posts': '帖子',
    'profile.comments': '评论',
    'profile.joined': '加入时间',
    'profile.editProfile': '编辑资料',
    'profile.sendMessage': '发送消息',
    'profile.activity': '动态',
    'profile.updates': '更新',
    'profile.settings': '设置',
    'messages.inbox': '收件箱',
    'messages.sent': '已发送',
    'messages.compose': '写消息',
    'messages.subject': '主题',
    'messages.content': '内容',
    'messages.send': '发送',
    'messages.noMessages': '没有消息',
    'blog.latest': '最新文章',
    'blog.readMore': '阅读更多',
    'blog.author': '作者',
    'blog.published': '发布于',
    'blog.related': '相关文章',
    'blog.minRead': '分钟阅读',
    'blog.backToBlog': '返回博客',
    'game.play': '开始游戏',
    'game.score': '分数',
    'game.highScore': '最高分',
    'game.leaderboard': '排行榜',
    'game.start': '开始',
    'game.gameOver': '游戏结束',
    'game.restart': '再玩一次',
    'seo.siteTitle': '手表交易论坛',
    'seo.siteDescription': '全球手表交易者和收藏家的首选社区',
    'seo.forumTitle': '手表交易论坛',
    'seo.blogTitle': '手表交易博客',
  },
  // Hindi
  hi: {
    'nav.home': 'होम',
    'nav.forum': 'फोरम',
    'nav.members': 'सदस्य',
    'nav.messages': 'संदेश',
    'nav.blog': 'ब्लॉग',
    'nav.game': 'गेम',
    'nav.search': 'खोज',
    'nav.login': 'लॉग इन',
    'nav.register': 'रजिस्टर',
    'nav.logout': 'लॉग आउट',
    'nav.profile': 'प्रोफाइल',
    'nav.settings': 'सेटिंग्स',
    'nav.admin': 'एडमिन',
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.success': 'सफल',
    'common.cancel': 'रद्द करें',
    'common.save': 'सहेजें',
    'common.delete': 'हटाएं',
    'common.edit': 'संपादित करें',
    'common.create': 'बनाएं',
    'common.search': 'खोजें',
    'common.filter': 'फ़िल्टर',
    'common.sort': 'क्रमबद्ध करें',
    'common.newest': 'नवीनतम',
    'common.oldest': 'सबसे पुराना',
    'common.hot': 'लोकप्रिय',
    'common.all': 'सभी',
    'forum.threads': 'थ्रेड्स',
    'forum.posts': 'पोस्ट्स',
    'forum.comments': 'टिप्पणियां',
    'forum.replies': 'जवाब',
    'forum.views': 'देखे गए',
    'forum.lastPost': 'अंतिम पोस्ट',
    'forum.noThreads': 'अभी तक कोई थ्रेड नहीं',
    'forum.createThread': 'थ्रेड बनाएं',
    'forum.reply': 'जवाब दें',
    'forum.subforums': 'उप-फोरम',
    'forum.searchPlaceholder': 'थ्रेड खोजें...',
    'auth.username': 'यूज़रनेम',
    'auth.password': 'पासवर्ड',
    'auth.email': 'ईमेल',
    'auth.phone': 'फोन नंबर',
    'auth.confirmPassword': 'पासवर्ड की पुष्टि',
    'auth.loginTitle': 'साइन इन',
    'auth.registerTitle': 'अकाउंट बनाएं',
    'auth.forgotPassword': 'पासवर्ड भूल गए?',
    'auth.rememberMe': 'मुझे याद रखें',
    'auth.noAccount': 'अकाउंट नहीं है?',
    'auth.haveAccount': 'पहले से अकाउंट है?',
    'auth.signUp': 'साइन अप',
    'auth.signIn': 'साइन इन',
    'auth.country': 'देश',
    'auth.language': 'भाषा',
    'auth.selectCountry': 'अपना देश चुनें',
    'auth.selectLanguage': 'अपनी भाषा चुनें',
    'profile.motto': 'मोटो',
    'profile.posts': 'पोस्ट्स',
    'profile.comments': 'टिप्पणियां',
    'profile.joined': 'जुड़ने की तारीख',
    'profile.editProfile': 'प्रोफाइल संपादित करें',
    'profile.sendMessage': 'संदेश भेजें',
    'profile.activity': 'गतिविधि',
    'profile.updates': 'अपडेट्स',
    'profile.settings': 'सेटिंग्स',
    'messages.inbox': 'इनबॉक्स',
    'messages.sent': 'भेजे गए',
    'messages.compose': 'लिखें',
    'messages.subject': 'विषय',
    'messages.content': 'संदेश',
    'messages.send': 'भेजें',
    'messages.noMessages': 'कोई संदेश नहीं',
    'blog.latest': 'नवीनतम लेख',
    'blog.readMore': 'और पढ़ें',
    'blog.author': 'लेखक',
    'blog.published': 'प्रकाशित',
    'blog.related': 'संबंधित लेख',
    'blog.minRead': 'मिनट पढ़ें',
    'blog.backToBlog': 'ब्लॉग पर वापस',
    'game.play': 'खेलें',
    'game.score': 'स्कोर',
    'game.highScore': 'उच्चतम स्कोर',
    'game.leaderboard': 'लीडरबोर्ड',
    'game.start': 'शुरू करें',
    'game.gameOver': 'गेम ओवर',
    'game.restart': 'फिर से खेलें',
    'seo.siteTitle': 'घड़ी ट्रेडिंग फोरम',
    'seo.siteDescription': 'दुनिया भर में घड़ी व्यापारियों और संग्रहकर्ताओं के लिए प्रमुख समुदाय',
    'seo.forumTitle': 'घड़ी ट्रेडिंग फोरम',
    'seo.blogTitle': 'घड़ी ट्रेडिंग ब्लॉग',
  },
  // Spanish
  es: {
    'nav.home': 'Inicio',
    'nav.forum': 'Foro',
    'nav.members': 'Miembros',
    'nav.messages': 'Mensajes',
    'nav.blog': 'Blog',
    'nav.game': 'Juego',
    'nav.search': 'Buscar',
    'nav.login': 'Iniciar sesión',
    'nav.register': 'Registrarse',
    'nav.logout': 'Cerrar sesión',
    'nav.profile': 'Perfil',
    'nav.settings': 'Configuración',
    'nav.admin': 'Admin',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.create': 'Crear',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.newest': 'Más reciente',
    'common.oldest': 'Más antiguo',
    'common.hot': 'Popular',
    'common.all': 'Todo',
    'forum.threads': 'Hilos',
    'forum.posts': 'Publicaciones',
    'forum.comments': 'Comentarios',
    'forum.replies': 'Respuestas',
    'forum.views': 'Vistas',
    'forum.lastPost': 'Última publicación',
    'forum.noThreads': 'Aún no hay hilos',
    'forum.createThread': 'Crear hilo',
    'forum.reply': 'Responder',
    'forum.subforums': 'Subforos',
    'forum.searchPlaceholder': 'Buscar hilos...',
    'auth.username': 'Nombre de usuario',
    'auth.password': 'Contraseña',
    'auth.email': 'Correo electrónico',
    'auth.phone': 'Teléfono',
    'auth.confirmPassword': 'Confirmar contraseña',
    'auth.loginTitle': 'Iniciar sesión',
    'auth.registerTitle': 'Crear cuenta',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.rememberMe': 'Recuérdame',
    'auth.noAccount': '¿No tienes cuenta?',
    'auth.haveAccount': '¿Ya tienes cuenta?',
    'auth.signUp': 'Registrarse',
    'auth.signIn': 'Iniciar sesión',
    'auth.country': 'País',
    'auth.language': 'Idioma',
    'auth.selectCountry': 'Selecciona tu país',
    'auth.selectLanguage': 'Selecciona tu idioma',
    'profile.motto': 'Lema',
    'profile.posts': 'Publicaciones',
    'profile.comments': 'Comentarios',
    'profile.joined': 'Se unió',
    'profile.editProfile': 'Editar perfil',
    'profile.sendMessage': 'Enviar mensaje',
    'profile.activity': 'Actividad',
    'profile.updates': 'Actualizaciones',
    'profile.settings': 'Configuración',
    'messages.inbox': 'Bandeja de entrada',
    'messages.sent': 'Enviados',
    'messages.compose': 'Redactar',
    'messages.subject': 'Asunto',
    'messages.content': 'Mensaje',
    'messages.send': 'Enviar',
    'messages.noMessages': 'No hay mensajes',
    'blog.latest': 'Últimos artículos',
    'blog.readMore': 'Leer más',
    'blog.author': 'Autor',
    'blog.published': 'Publicado',
    'blog.related': 'Artículos relacionados',
    'blog.minRead': 'min de lectura',
    'blog.backToBlog': 'Volver al blog',
    'game.play': 'Jugar',
    'game.score': 'Puntuación',
    'game.highScore': 'Puntuación máxima',
    'game.leaderboard': 'Clasificación',
    'game.start': 'Iniciar',
    'game.gameOver': 'Juego terminado',
    'game.restart': 'Jugar de nuevo',
    'seo.siteTitle': 'Foro de Intercambio de Relojes',
    'seo.siteDescription': 'La principal comunidad para comerciantes y coleccionistas de relojes de todo el mundo',
    'seo.forumTitle': 'Foro de Intercambio de Relojes',
    'seo.blogTitle': 'Blog de Intercambio de Relojes',
  },
  // French
  fr: {
    'nav.home': 'Accueil',
    'nav.forum': 'Forum',
    'nav.members': 'Membres',
    'nav.messages': 'Messages',
    'nav.blog': 'Blog',
    'nav.game': 'Jeu',
    'nav.search': 'Rechercher',
    'nav.login': 'Connexion',
    'nav.register': 'S\'inscrire',
    'nav.logout': 'Déconnexion',
    'nav.profile': 'Profil',
    'nav.settings': 'Paramètres',
    'nav.admin': 'Admin',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.save': 'Enregistrer',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.create': 'Créer',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.sort': 'Trier',
    'common.newest': 'Plus récent',
    'common.oldest': 'Plus ancien',
    'common.hot': 'Populaire',
    'common.all': 'Tout',
    'forum.threads': 'Sujets',
    'forum.posts': 'Messages',
    'forum.comments': 'Commentaires',
    'forum.replies': 'Réponses',
    'forum.views': 'Vues',
    'forum.lastPost': 'Dernier message',
    'forum.noThreads': 'Aucun sujet pour l\'instant',
    'forum.createThread': 'Créer un sujet',
    'forum.reply': 'Répondre',
    'forum.subforums': 'Sous-forums',
    'forum.searchPlaceholder': 'Rechercher des sujets...',
    'auth.username': 'Nom d\'utilisateur',
    'auth.password': 'Mot de passe',
    'auth.email': 'Email',
    'auth.phone': 'Téléphone',
    'auth.confirmPassword': 'Confirmer le mot de passe',
    'auth.loginTitle': 'Connexion',
    'auth.registerTitle': 'Créer un compte',
    'auth.forgotPassword': 'Mot de passe oublié?',
    'auth.rememberMe': 'Se souvenir de moi',
    'auth.noAccount': 'Pas de compte?',
    'auth.haveAccount': 'Déjà un compte?',
    'auth.signUp': 'S\'inscrire',
    'auth.signIn': 'Connexion',
    'auth.country': 'Pays',
    'auth.language': 'Langue',
    'auth.selectCountry': 'Sélectionnez votre pays',
    'auth.selectLanguage': 'Sélectionnez votre langue',
    'profile.motto': 'Devise',
    'profile.posts': 'Messages',
    'profile.comments': 'Commentaires',
    'profile.joined': 'Inscrit depuis',
    'profile.editProfile': 'Modifier le profil',
    'profile.sendMessage': 'Envoyer un message',
    'profile.activity': 'Activité',
    'profile.updates': 'Mises à jour',
    'profile.settings': 'Paramètres',
    'messages.inbox': 'Boîte de réception',
    'messages.sent': 'Envoyés',
    'messages.compose': 'Nouveau',
    'messages.subject': 'Objet',
    'messages.content': 'Message',
    'messages.send': 'Envoyer',
    'messages.noMessages': 'Aucun message',
    'blog.latest': 'Derniers articles',
    'blog.readMore': 'Lire la suite',
    'blog.author': 'Auteur',
    'blog.published': 'Publié',
    'blog.related': 'Articles connexes',
    'blog.minRead': 'min de lecture',
    'blog.backToBlog': 'Retour au blog',
    'game.play': 'Jouer',
    'game.score': 'Score',
    'game.highScore': 'Meilleur score',
    'game.leaderboard': 'Classement',
    'game.start': 'Démarrer',
    'game.gameOver': 'Partie terminée',
    'game.restart': 'Rejouer',
    'seo.siteTitle': 'Forum d\'Échange de Montres',
    'seo.siteDescription': 'La première communauté pour les traders et collectionneurs de montres du monde entier',
    'seo.forumTitle': 'Forum d\'Échange de Montres',
    'seo.blogTitle': 'Blog d\'Échange de Montres',
  },
  // Arabic (RTL)
  ar: {
    'nav.home': 'الرئيسية',
    'nav.forum': 'المنتدى',
    'nav.members': 'الأعضاء',
    'nav.messages': 'الرسائل',
    'nav.blog': 'المدونة',
    'nav.game': 'اللعبة',
    'nav.search': 'بحث',
    'nav.login': 'تسجيل الدخول',
    'nav.register': 'التسجيل',
    'nav.logout': 'تسجيل الخروج',
    'nav.profile': 'الملف الشخصي',
    'nav.settings': 'الإعدادات',
    'nav.admin': 'المشرف',
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجاح',
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.create': 'إنشاء',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.sort': 'ترتيب',
    'common.newest': 'الأحدث',
    'common.oldest': 'الأقدم',
    'common.hot': 'الشائع',
    'common.all': 'الكل',
    'forum.threads': 'المواضيع',
    'forum.posts': 'المشاركات',
    'forum.comments': 'التعليقات',
    'forum.replies': 'الردود',
    'forum.views': 'المشاهدات',
    'forum.lastPost': 'آخر مشاركة',
    'forum.noThreads': 'لا توجد مواضيع بعد',
    'forum.createThread': 'إنشاء موضوع',
    'forum.reply': 'رد',
    'forum.subforums': 'المنتديات الفرعية',
    'forum.searchPlaceholder': 'البحث في المواضيع...',
    'auth.username': 'اسم المستخدم',
    'auth.password': 'كلمة المرور',
    'auth.email': 'البريد الإلكتروني',
    'auth.phone': 'رقم الهاتف',
    'auth.confirmPassword': 'تأكيد كلمة المرور',
    'auth.loginTitle': 'تسجيل الدخول',
    'auth.registerTitle': 'إنشاء حساب',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.rememberMe': 'تذكرني',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.haveAccount': 'لديك حساب بالفعل؟',
    'auth.signUp': 'التسجيل',
    'auth.signIn': 'تسجيل الدخول',
    'auth.country': 'الدولة',
    'auth.language': 'اللغة',
    'auth.selectCountry': 'اختر دولتك',
    'auth.selectLanguage': 'اختر لغتك',
    'profile.motto': 'الشعار',
    'profile.posts': 'المشاركات',
    'profile.comments': 'التعليقات',
    'profile.joined': 'تاريخ الانضمام',
    'profile.editProfile': 'تعديل الملف الشخصي',
    'profile.sendMessage': 'إرسال رسالة',
    'profile.activity': 'النشاط',
    'profile.updates': 'التحديثات',
    'profile.settings': 'الإعدادات',
    'messages.inbox': 'صندوق الوارد',
    'messages.sent': 'المرسلة',
    'messages.compose': 'كتابة',
    'messages.subject': 'الموضوع',
    'messages.content': 'الرسالة',
    'messages.send': 'إرسال',
    'messages.noMessages': 'لا توجد رسائل',
    'blog.latest': 'أحدث المقالات',
    'blog.readMore': 'قراءة المزيد',
    'blog.author': 'المؤلف',
    'blog.published': 'نُشر في',
    'blog.related': 'مقالات ذات صلة',
    'blog.minRead': 'دقيقة قراءة',
    'blog.backToBlog': 'العودة إلى المدونة',
    'game.play': 'لعب',
    'game.score': 'النقاط',
    'game.highScore': 'أعلى نقاط',
    'game.leaderboard': 'لوحة المتصدرين',
    'game.start': 'بدء',
    'game.gameOver': 'انتهت اللعبة',
    'game.restart': 'إعادة اللعب',
    'seo.siteTitle': 'منتدى تداول الساعات',
    'seo.siteDescription': 'المجتمع الرائد لتجار وجامعي الساعات حول العالم',
    'seo.forumTitle': 'منتدى تداول الساعات',
    'seo.blogTitle': 'مدونة تداول الساعات',
  },
  // Bengali
  bn: {
    'nav.home': 'হোম',
    'nav.forum': 'ফোরাম',
    'nav.members': 'সদস্য',
    'nav.messages': 'বার্তা',
    'nav.blog': 'ব্লগ',
    'nav.game': 'গেম',
    'nav.search': 'অনুসন্ধান',
    'nav.login': 'লগইন',
    'nav.register': 'নিবন্ধন',
    'nav.logout': 'লগআউট',
    'nav.profile': 'প্রোফাইল',
    'nav.settings': 'সেটিংস',
    'nav.admin': 'অ্যাডমিন',
    'common.loading': 'লোড হচ্ছে...',
    'common.error': 'ত্রুটি',
    'common.success': 'সফল',
    'common.cancel': 'বাতিল',
    'common.save': 'সংরক্ষণ',
    'common.delete': 'মুছুন',
    'common.edit': 'সম্পাদনা',
    'common.create': 'তৈরি করুন',
    'common.search': 'অনুসন্ধান',
    'common.filter': 'ফিল্টার',
    'common.sort': 'সাজান',
    'common.newest': 'নতুনতম',
    'common.oldest': 'পুরাতন',
    'common.hot': 'জনপ্রিয়',
    'common.all': 'সব',
    'forum.threads': 'থ্রেড',
    'forum.posts': 'পোস্ট',
    'forum.comments': 'মন্তব্য',
    'forum.replies': 'উত্তর',
    'forum.views': 'দেখা',
    'forum.lastPost': 'শেষ পোস্ট',
    'forum.noThreads': 'এখনো কোনো থ্রেড নেই',
    'forum.createThread': 'থ্রেড তৈরি করুন',
    'forum.reply': 'উত্তর দিন',
    'forum.subforums': 'উপ-ফোরাম',
    'forum.searchPlaceholder': 'থ্রেড অনুসন্ধান করুন...',
    'auth.username': 'ইউজারনেম',
    'auth.password': 'পাসওয়ার্ড',
    'auth.email': 'ইমেইল',
    'auth.phone': 'ফোন নম্বর',
    'auth.confirmPassword': 'পাসওয়ার্ড নিশ্চিত করুন',
    'auth.loginTitle': 'সাইন ইন',
    'auth.registerTitle': 'অ্যাকাউন্ট তৈরি করুন',
    'auth.forgotPassword': 'পাসওয়ার্ড ভুলে গেছেন?',
    'auth.rememberMe': 'আমাকে মনে রাখুন',
    'auth.noAccount': 'অ্যাকাউন্ট নেই?',
    'auth.haveAccount': 'অ্যাকাউন্ট আছে?',
    'auth.signUp': 'সাইন আপ',
    'auth.signIn': 'সাইন ইন',
    'auth.country': 'দেশ',
    'auth.language': 'ভাষা',
    'auth.selectCountry': 'আপনার দেশ নির্বাচন করুন',
    'auth.selectLanguage': 'আপনার ভাষা নির্বাচন করুন',
    'profile.motto': 'মোটো',
    'profile.posts': 'পোস্ট',
    'profile.comments': 'মন্তব্য',
    'profile.joined': 'যোগদানের তারিখ',
    'profile.editProfile': 'প্রোফাইল সম্পাদনা',
    'profile.sendMessage': 'বার্তা পাঠান',
    'profile.activity': 'কার্যকলাপ',
    'profile.updates': 'আপডেট',
    'profile.settings': 'সেটিংস',
    'messages.inbox': 'ইনবক্স',
    'messages.sent': 'প্রেরিত',
    'messages.compose': 'লিখুন',
    'messages.subject': 'বিষয়',
    'messages.content': 'বার্তা',
    'messages.send': 'পাঠান',
    'messages.noMessages': 'কোনো বার্তা নেই',
    'blog.latest': 'সর্বশেষ নিবন্ধ',
    'blog.readMore': 'আরও পড়ুন',
    'blog.author': 'লেখক',
    'blog.published': 'প্রকাশিত',
    'blog.related': 'সম্পর্কিত নিবন্ধ',
    'blog.minRead': 'মিনিট পড়া',
    'blog.backToBlog': 'ব্লগে ফিরুন',
    'game.play': 'খেলুন',
    'game.score': 'স্কোর',
    'game.highScore': 'সর্বোচ্চ স্কোর',
    'game.leaderboard': 'লিডারবোর্ড',
    'game.start': 'শুরু করুন',
    'game.gameOver': 'গেম ওভার',
    'game.restart': 'আবার খেলুন',
    'seo.siteTitle': 'ঘড়ি ট্রেডিং ফোরাম',
    'seo.siteDescription': 'বিশ্বজুড়ে ঘড়ি ব্যবসায়ী এবং সংগ্রাহকদের জন্য প্রধান সম্প্রদায়',
    'seo.forumTitle': 'ঘড়ি ট্রেডিং ফোরাম',
    'seo.blogTitle': 'ঘড়ি ট্রেডিং ব্লগ',
  },
  // Portuguese
  pt: {
    'nav.home': 'Início',
    'nav.forum': 'Fórum',
    'nav.members': 'Membros',
    'nav.messages': 'Mensagens',
    'nav.blog': 'Blog',
    'nav.game': 'Jogo',
    'nav.search': 'Pesquisar',
    'nav.login': 'Entrar',
    'nav.register': 'Registar',
    'nav.logout': 'Sair',
    'nav.profile': 'Perfil',
    'nav.settings': 'Definições',
    'nav.admin': 'Admin',
    'common.loading': 'A carregar...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.create': 'Criar',
    'common.search': 'Pesquisar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.newest': 'Mais recente',
    'common.oldest': 'Mais antigo',
    'common.hot': 'Popular',
    'common.all': 'Tudo',
    'forum.threads': 'Tópicos',
    'forum.posts': 'Publicações',
    'forum.comments': 'Comentários',
    'forum.replies': 'Respostas',
    'forum.views': 'Visualizações',
    'forum.lastPost': 'Última publicação',
    'forum.noThreads': 'Ainda sem tópicos',
    'forum.createThread': 'Criar tópico',
    'forum.reply': 'Responder',
    'forum.subforums': 'Subfóruns',
    'forum.searchPlaceholder': 'Pesquisar tópicos...',
    'auth.username': 'Nome de utilizador',
    'auth.password': 'Palavra-passe',
    'auth.email': 'Email',
    'auth.phone': 'Telefone',
    'auth.confirmPassword': 'Confirmar palavra-passe',
    'auth.loginTitle': 'Iniciar sessão',
    'auth.registerTitle': 'Criar conta',
    'auth.forgotPassword': 'Esqueceu-se da palavra-passe?',
    'auth.rememberMe': 'Lembrar-me',
    'auth.noAccount': 'Não tem conta?',
    'auth.haveAccount': 'Já tem conta?',
    'auth.signUp': 'Registar',
    'auth.signIn': 'Entrar',
    'auth.country': 'País',
    'auth.language': 'Idioma',
    'auth.selectCountry': 'Selecione o seu país',
    'auth.selectLanguage': 'Selecione o seu idioma',
    'profile.motto': 'Lema',
    'profile.posts': 'Publicações',
    'profile.comments': 'Comentários',
    'profile.joined': 'Registado desde',
    'profile.editProfile': 'Editar perfil',
    'profile.sendMessage': 'Enviar mensagem',
    'profile.activity': 'Atividade',
    'profile.updates': 'Atualizações',
    'profile.settings': 'Definições',
    'messages.inbox': 'Caixa de entrada',
    'messages.sent': 'Enviadas',
    'messages.compose': 'Compor',
    'messages.subject': 'Assunto',
    'messages.content': 'Mensagem',
    'messages.send': 'Enviar',
    'messages.noMessages': 'Sem mensagens',
    'blog.latest': 'Artigos mais recentes',
    'blog.readMore': 'Ler mais',
    'blog.author': 'Autor',
    'blog.published': 'Publicado',
    'blog.related': 'Artigos relacionados',
    'blog.minRead': 'min de leitura',
    'blog.backToBlog': 'Voltar ao blog',
    'game.play': 'Jogar',
    'game.score': 'Pontuação',
    'game.highScore': 'Pontuação máxima',
    'game.leaderboard': 'Classificação',
    'game.start': 'Iniciar',
    'game.gameOver': 'Fim do jogo',
    'game.restart': 'Jogar novamente',
    'seo.siteTitle': 'Fórum de Negociação de Relógios',
    'seo.siteDescription': 'A principal comunidade para negociantes e colecionadores de relógios em todo o mundo',
    'seo.forumTitle': 'Fórum de Negociação de Relógios',
    'seo.blogTitle': 'Blog de Negociação de Relógios',
  },
  // Russian
  ru: {
    'nav.home': 'Главная',
    'nav.forum': 'Форум',
    'nav.members': 'Участники',
    'nav.messages': 'Сообщения',
    'nav.blog': 'Блог',
    'nav.game': 'Игра',
    'nav.search': 'Поиск',
    'nav.login': 'Вход',
    'nav.register': 'Регистрация',
    'nav.logout': 'Выход',
    'nav.profile': 'Профиль',
    'nav.settings': 'Настройки',
    'nav.admin': 'Админ',
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'common.success': 'Успех',
    'common.cancel': 'Отмена',
    'common.save': 'Сохранить',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.create': 'Создать',
    'common.search': 'Поиск',
    'common.filter': 'Фильтр',
    'common.sort': 'Сортировка',
    'common.newest': 'Новые',
    'common.oldest': 'Старые',
    'common.hot': 'Популярные',
    'common.all': 'Все',
    'forum.threads': 'Темы',
    'forum.posts': 'Посты',
    'forum.comments': 'Комментарии',
    'forum.replies': 'Ответы',
    'forum.views': 'Просмотры',
    'forum.lastPost': 'Последний пост',
    'forum.noThreads': 'Пока нет тем',
    'forum.createThread': 'Создать тему',
    'forum.reply': 'Ответить',
    'forum.subforums': 'Подфорумы',
    'forum.searchPlaceholder': 'Поиск тем...',
    'auth.username': 'Имя пользователя',
    'auth.password': 'Пароль',
    'auth.email': 'Email',
    'auth.phone': 'Телефон',
    'auth.confirmPassword': 'Подтвердите пароль',
    'auth.loginTitle': 'Вход',
    'auth.registerTitle': 'Создать аккаунт',
    'auth.forgotPassword': 'Забыли пароль?',
    'auth.rememberMe': 'Запомнить меня',
    'auth.noAccount': 'Нет аккаунта?',
    'auth.haveAccount': 'Уже есть аккаунт?',
    'auth.signUp': 'Регистрация',
    'auth.signIn': 'Вход',
    'auth.country': 'Страна',
    'auth.language': 'Язык',
    'auth.selectCountry': 'Выберите вашу страну',
    'auth.selectLanguage': 'Выберите ваш язык',
    'profile.motto': 'Девиз',
    'profile.posts': 'Посты',
    'profile.comments': 'Комментарии',
    'profile.joined': 'Присоединился',
    'profile.editProfile': 'Редактировать профиль',
    'profile.sendMessage': 'Отправить сообщение',
    'profile.activity': 'Активность',
    'profile.updates': 'Обновления',
    'profile.settings': 'Настройки',
    'messages.inbox': 'Входящие',
    'messages.sent': 'Отправленные',
    'messages.compose': 'Написать',
    'messages.subject': 'Тема',
    'messages.content': 'Сообщение',
    'messages.send': 'Отправить',
    'messages.noMessages': 'Нет сообщений',
    'blog.latest': 'Последние статьи',
    'blog.readMore': 'Читать далее',
    'blog.author': 'Автор',
    'blog.published': 'Опубликовано',
    'blog.related': 'Похожие статьи',
    'blog.minRead': 'мин чтения',
    'blog.backToBlog': 'Назад в блог',
    'game.play': 'Играть',
    'game.score': 'Счет',
    'game.highScore': 'Рекорд',
    'game.leaderboard': 'Таблица лидеров',
    'game.start': 'Начать',
    'game.gameOver': 'Игра окончена',
    'game.restart': 'Играть снова',
    'seo.siteTitle': 'Форум Торговли Часами',
    'seo.siteDescription': 'Ведущее сообщество для торговцев и коллекционеров часов по всему миру',
    'seo.forumTitle': 'Форум Торговли Часами',
    'seo.blogTitle': 'Блог Торговли Часами',
  },
  // Urdu (RTL)
  ur: {
    'nav.home': 'ہوم',
    'nav.forum': 'فورم',
    'nav.members': 'ممبرز',
    'nav.messages': 'پیغامات',
    'nav.blog': 'بلاگ',
    'nav.game': 'گیم',
    'nav.search': 'تلاش',
    'nav.login': 'لاگ ان',
    'nav.register': 'رجسٹر',
    'nav.logout': 'لاگ آؤٹ',
    'nav.profile': 'پروفائل',
    'nav.settings': 'سیٹنگز',
    'nav.admin': 'ایڈمن',
    'common.loading': 'لوڈ ہو رہا ہے...',
    'common.error': 'خرابی',
    'common.success': 'کامیابی',
    'common.cancel': 'منسوخ',
    'common.save': 'محفوظ کریں',
    'common.delete': 'حذف کریں',
    'common.edit': 'ترمیم',
    'common.create': 'بنائیں',
    'common.search': 'تلاش',
    'common.filter': 'فلٹر',
    'common.sort': 'ترتیب',
    'common.newest': 'تازہ ترین',
    'common.oldest': 'قدیم ترین',
    'common.hot': 'مشہور',
    'common.all': 'سب',
    'forum.threads': 'تھریڈز',
    'forum.posts': 'پوسٹس',
    'forum.comments': 'تبصرے',
    'forum.replies': 'جوابات',
    'forum.views': 'دیکھے گئے',
    'forum.lastPost': 'آخری پوسٹ',
    'forum.noThreads': 'ابھی تک کوئی تھریڈ نہیں',
    'forum.createThread': 'تھریڈ بنائیں',
    'forum.reply': 'جواب دیں',
    'forum.subforums': 'ذیلی فورمز',
    'forum.searchPlaceholder': 'تھریڈز تلاش کریں...',
    'auth.username': 'صارف نام',
    'auth.password': 'پاس ورڈ',
    'auth.email': 'ای میل',
    'auth.phone': 'فون نمبر',
    'auth.confirmPassword': 'پاس ورڈ تصدیق کریں',
    'auth.loginTitle': 'سائن ان',
    'auth.registerTitle': 'اکاؤنٹ بنائیں',
    'auth.forgotPassword': 'پاس ورڈ بھول گئے؟',
    'auth.rememberMe': 'مجھے یاد رکھیں',
    'auth.noAccount': 'اکاؤنٹ نہیں ہے؟',
    'auth.haveAccount': 'پہلے سے اکاؤنٹ ہے؟',
    'auth.signUp': 'سائن اپ',
    'auth.signIn': 'سائن ان',
    'auth.country': 'ملک',
    'auth.language': 'زبان',
    'auth.selectCountry': 'اپنا ملک منتخب کریں',
    'auth.selectLanguage': 'اپنی زبان منتخب کریں',
    'profile.motto': 'نعرہ',
    'profile.posts': 'پوسٹس',
    'profile.comments': 'تبصرے',
    'profile.joined': 'شمولیت کی تاریخ',
    'profile.editProfile': 'پروفائل ترمیم',
    'profile.sendMessage': 'پیغام بھیجیں',
    'profile.activity': 'سرگرمی',
    'profile.updates': 'اپڈیٹس',
    'profile.settings': 'سیٹنگز',
    'messages.inbox': 'ان باکس',
    'messages.sent': 'بھیجے گئے',
    'messages.compose': 'لکھیں',
    'messages.subject': 'موضوع',
    'messages.content': 'پیغام',
    'messages.send': 'بھیجیں',
    'messages.noMessages': 'کوئی پیغام نہیں',
    'blog.latest': 'تازہ ترین مضامین',
    'blog.readMore': 'مزید پڑھیں',
    'blog.author': 'مصنف',
    'blog.published': 'شائع شدہ',
    'blog.related': 'متعلقہ مضامین',
    'blog.minRead': 'منٹ پڑھیں',
    'blog.backToBlog': 'بلاگ پر واپس',
    'game.play': 'کھیلیں',
    'game.score': 'اسکور',
    'game.highScore': 'اعلی اسکور',
    'game.leaderboard': 'لیڈر بورڈ',
    'game.start': 'شروع کریں',
    'game.gameOver': 'گیم ختم',
    'game.restart': 'دوبارہ کھیلیں',
    'seo.siteTitle': 'گھڑی ٹریڈنگ فورم',
    'seo.siteDescription': 'دنیا بھر میں گھڑی کے تاجروں اور جمع کرنے والوں کے لیے سر فہرست کمیونٹی',
    'seo.forumTitle': 'گھڑی ٹریڈنگ فورم',
    'seo.blogTitle': 'گھڑی ٹریڈنگ بلاگ',
  },
  // Indonesian
  id: {
    'nav.home': 'Beranda',
    'nav.forum': 'Forum',
    'nav.members': 'Anggota',
    'nav.messages': 'Pesan',
    'nav.blog': 'Blog',
    'nav.game': 'Permainan',
    'nav.search': 'Cari',
    'nav.login': 'Masuk',
    'nav.register': 'Daftar',
    'nav.logout': 'Keluar',
    'nav.profile': 'Profil',
    'nav.settings': 'Pengaturan',
    'nav.admin': 'Admin',
    'common.loading': 'Memuat...',
    'common.error': 'Kesalahan',
    'common.success': 'Berhasil',
    'common.cancel': 'Batal',
    'common.save': 'Simpan',
    'common.delete': 'Hapus',
    'common.edit': 'Edit',
    'common.create': 'Buat',
    'common.search': 'Cari',
    'common.filter': 'Filter',
    'common.sort': 'Urutkan',
    'common.newest': 'Terbaru',
    'common.oldest': 'Terlama',
    'common.hot': 'Populer',
    'common.all': 'Semua',
    'forum.threads': 'Thread',
    'forum.posts': 'Posting',
    'forum.comments': 'Komentar',
    'forum.replies': 'Balasan',
    'forum.views': 'Dilihat',
    'forum.lastPost': 'Posting Terakhir',
    'forum.noThreads': 'Belum ada thread',
    'forum.createThread': 'Buat Thread',
    'forum.reply': 'Balas',
    'forum.subforums': 'Sub-forum',
    'forum.searchPlaceholder': 'Cari thread...',
    'auth.username': 'Nama pengguna',
    'auth.password': 'Kata sandi',
    'auth.email': 'Email',
    'auth.phone': 'Nomor telepon',
    'auth.confirmPassword': 'Konfirmasi kata sandi',
    'auth.loginTitle': 'Masuk',
    'auth.registerTitle': 'Buat Akun',
    'auth.forgotPassword': 'Lupa kata sandi?',
    'auth.rememberMe': 'Ingat saya',
    'auth.noAccount': 'Belum punya akun?',
    'auth.haveAccount': 'Sudah punya akun?',
    'auth.signUp': 'Daftar',
    'auth.signIn': 'Masuk',
    'auth.country': 'Negara',
    'auth.language': 'Bahasa',
    'auth.selectCountry': 'Pilih negara Anda',
    'auth.selectLanguage': 'Pilih bahasa Anda',
    'profile.motto': 'Moto',
    'profile.posts': 'Posting',
    'profile.comments': 'Komentar',
    'profile.joined': 'Bergabung',
    'profile.editProfile': 'Edit Profil',
    'profile.sendMessage': 'Kirim Pesan',
    'profile.activity': 'Aktivitas',
    'profile.updates': 'Pembaruan',
    'profile.settings': 'Pengaturan',
    'messages.inbox': 'Kotak Masuk',
    'messages.sent': 'Terkirim',
    'messages.compose': 'Tulis',
    'messages.subject': 'Subjek',
    'messages.content': 'Pesan',
    'messages.send': 'Kirim',
    'messages.noMessages': 'Tidak ada pesan',
    'blog.latest': 'Artikel Terbaru',
    'blog.readMore': 'Baca Selengkapnya',
    'blog.author': 'Penulis',
    'blog.published': 'Dipublikasikan',
    'blog.related': 'Artikel Terkait',
    'blog.minRead': 'mnt baca',
    'blog.backToBlog': 'Kembali ke Blog',
    'game.play': 'Main',
    'game.score': 'Skor',
    'game.highScore': 'Skor Tertinggi',
    'game.leaderboard': 'Papan Peringkat',
    'game.start': 'Mulai',
    'game.gameOver': 'Permainan Berakhir',
    'game.restart': 'Main Lagi',
    'seo.siteTitle': 'Forum Perdagangan Jam Tangan',
    'seo.siteDescription': 'Komunitas utama untuk pedagang dan kolektor jam tangan di seluruh dunia',
    'seo.forumTitle': 'Forum Perdagangan Jam Tangan',
    'seo.blogTitle': 'Blog Perdagangan Jam Tangan',
  },
  // German
  de: {
    'nav.home': 'Startseite',
    'nav.forum': 'Forum',
    'nav.members': 'Mitglieder',
    'nav.messages': 'Nachrichten',
    'nav.blog': 'Blog',
    'nav.game': 'Spiel',
    'nav.search': 'Suchen',
    'nav.login': 'Anmelden',
    'nav.register': 'Registrieren',
    'nav.logout': 'Abmelden',
    'nav.profile': 'Profil',
    'nav.settings': 'Einstellungen',
    'nav.admin': 'Admin',
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.cancel': 'Abbrechen',
    'common.save': 'Speichern',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.create': 'Erstellen',
    'common.search': 'Suchen',
    'common.filter': 'Filter',
    'common.sort': 'Sortieren',
    'common.newest': 'Neueste',
    'common.oldest': 'Älteste',
    'common.hot': 'Beliebt',
    'common.all': 'Alle',
    'forum.threads': 'Themen',
    'forum.posts': 'Beiträge',
    'forum.comments': 'Kommentare',
    'forum.replies': 'Antworten',
    'forum.views': 'Aufrufe',
    'forum.lastPost': 'Letzter Beitrag',
    'forum.noThreads': 'Noch keine Themen',
    'forum.createThread': 'Thema erstellen',
    'forum.reply': 'Antworten',
    'forum.subforums': 'Unterforen',
    'forum.searchPlaceholder': 'Themen durchsuchen...',
    'auth.username': 'Benutzername',
    'auth.password': 'Passwort',
    'auth.email': 'E-Mail',
    'auth.phone': 'Telefon',
    'auth.confirmPassword': 'Passwort bestätigen',
    'auth.loginTitle': 'Anmelden',
    'auth.registerTitle': 'Konto erstellen',
    'auth.forgotPassword': 'Passwort vergessen?',
    'auth.rememberMe': 'Angemeldet bleiben',
    'auth.noAccount': 'Noch kein Konto?',
    'auth.haveAccount': 'Bereits ein Konto?',
    'auth.signUp': 'Registrieren',
    'auth.signIn': 'Anmelden',
    'auth.country': 'Land',
    'auth.language': 'Sprache',
    'auth.selectCountry': 'Wählen Sie Ihr Land',
    'auth.selectLanguage': 'Wählen Sie Ihre Sprache',
    'profile.motto': 'Motto',
    'profile.posts': 'Beiträge',
    'profile.comments': 'Kommentare',
    'profile.joined': 'Beigetreten',
    'profile.editProfile': 'Profil bearbeiten',
    'profile.sendMessage': 'Nachricht senden',
    'profile.activity': 'Aktivität',
    'profile.updates': 'Updates',
    'profile.settings': 'Einstellungen',
    'messages.inbox': 'Posteingang',
    'messages.sent': 'Gesendet',
    'messages.compose': 'Verfassen',
    'messages.subject': 'Betreff',
    'messages.content': 'Nachricht',
    'messages.send': 'Senden',
    'messages.noMessages': 'Keine Nachrichten',
    'blog.latest': 'Neueste Artikel',
    'blog.readMore': 'Weiterlesen',
    'blog.author': 'Autor',
    'blog.published': 'Veröffentlicht',
    'blog.related': 'Verwandte Artikel',
    'blog.minRead': 'Min. Lesezeit',
    'blog.backToBlog': 'Zurück zum Blog',
    'game.play': 'Spielen',
    'game.score': 'Punkte',
    'game.highScore': 'Highscore',
    'game.leaderboard': 'Bestenliste',
    'game.start': 'Starten',
    'game.gameOver': 'Spiel vorbei',
    'game.restart': 'Nochmal spielen',
    'seo.siteTitle': 'Uhrenhandel Forum',
    'seo.siteDescription': 'Die führende Community für Uhrenhändler und Sammler weltweit',
    'seo.forumTitle': 'Uhrenhandel Forum',
    'seo.blogTitle': 'Uhrenhandel Blog',
  },
  // Japanese
  ja: {
    'nav.home': 'ホーム',
    'nav.forum': 'フォーラム',
    'nav.members': 'メンバー',
    'nav.messages': 'メッセージ',
    'nav.blog': 'ブログ',
    'nav.game': 'ゲーム',
    'nav.search': '検索',
    'nav.login': 'ログイン',
    'nav.register': '登録',
    'nav.logout': 'ログアウト',
    'nav.profile': 'プロフィール',
    'nav.settings': '設定',
    'nav.admin': '管理',
    'common.loading': '読み込み中...',
    'common.error': 'エラー',
    'common.success': '成功',
    'common.cancel': 'キャンセル',
    'common.save': '保存',
    'common.delete': '削除',
    'common.edit': '編集',
    'common.create': '作成',
    'common.search': '検索',
    'common.filter': 'フィルター',
    'common.sort': '並び替え',
    'common.newest': '最新',
    'common.oldest': '最古',
    'common.hot': '人気',
    'common.all': 'すべて',
    'forum.threads': 'スレッド',
    'forum.posts': '投稿',
    'forum.comments': 'コメント',
    'forum.replies': '返信',
    'forum.views': '閲覧数',
    'forum.lastPost': '最終投稿',
    'forum.noThreads': 'スレッドがありません',
    'forum.createThread': 'スレッド作成',
    'forum.reply': '返信',
    'forum.subforums': 'サブフォーラム',
    'forum.searchPlaceholder': 'スレッドを検索...',
    'auth.username': 'ユーザー名',
    'auth.password': 'パスワード',
    'auth.email': 'メールアドレス',
    'auth.phone': '電話番号',
    'auth.confirmPassword': 'パスワード確認',
    'auth.loginTitle': 'ログイン',
    'auth.registerTitle': 'アカウント作成',
    'auth.forgotPassword': 'パスワードを忘れた？',
    'auth.rememberMe': 'ログイン状態を保持',
    'auth.noAccount': 'アカウントをお持ちでない？',
    'auth.haveAccount': 'すでにアカウントをお持ち？',
    'auth.signUp': '登録',
    'auth.signIn': 'ログイン',
    'auth.country': '国',
    'auth.language': '言語',
    'auth.selectCountry': '国を選択',
    'auth.selectLanguage': '言語を選択',
    'profile.motto': '座右の銘',
    'profile.posts': '投稿',
    'profile.comments': 'コメント',
    'profile.joined': '登録日',
    'profile.editProfile': 'プロフィール編集',
    'profile.sendMessage': 'メッセージ送信',
    'profile.activity': 'アクティビティ',
    'profile.updates': '更新',
    'profile.settings': '設定',
    'messages.inbox': '受信トレイ',
    'messages.sent': '送信済み',
    'messages.compose': '作成',
    'messages.subject': '件名',
    'messages.content': 'メッセージ',
    'messages.send': '送信',
    'messages.noMessages': 'メッセージがありません',
    'blog.latest': '最新記事',
    'blog.readMore': '続きを読む',
    'blog.author': '著者',
    'blog.published': '公開日',
    'blog.related': '関連記事',
    'blog.minRead': '分で読める',
    'blog.backToBlog': 'ブログに戻る',
    'game.play': 'プレイ',
    'game.score': 'スコア',
    'game.highScore': 'ハイスコア',
    'game.leaderboard': 'ランキング',
    'game.start': 'スタート',
    'game.gameOver': 'ゲームオーバー',
    'game.restart': 'もう一度プレイ',
    'seo.siteTitle': '時計取引フォーラム',
    'seo.siteDescription': '世界中の時計トレーダーとコレクターのためのプレミアコミュニティ',
    'seo.forumTitle': '時計取引フォーラム',
    'seo.blogTitle': '時計取引ブログ',
  },
  // Nigerian Pidgin
  pcm: {
    'nav.home': 'Home',
    'nav.forum': 'Forum',
    'nav.members': 'Members',
    'nav.messages': 'Messages',
    'nav.blog': 'Blog',
    'nav.game': 'Game',
    'nav.search': 'Search',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.logout': 'Logout',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.admin': 'Admin',
    'common.loading': 'Dey load...',
    'common.error': 'Wahala',
    'common.success': 'E work',
    'common.cancel': 'Cancel',
    'common.save': 'Save am',
    'common.delete': 'Delete am',
    'common.edit': 'Edit am',
    'common.create': 'Create',
    'common.search': 'Find am',
    'common.filter': 'Filter',
    'common.sort': 'Arrange am',
    'common.newest': 'Newest',
    'common.oldest': 'Oldest',
    'common.hot': 'Hot',
    'common.all': 'All',
    'forum.threads': 'Threads',
    'forum.posts': 'Posts',
    'forum.comments': 'Comments',
    'forum.replies': 'Replies',
    'forum.views': 'Views',
    'forum.lastPost': 'Last Post',
    'forum.noThreads': 'No thread yet',
    'forum.createThread': 'Create Thread',
    'forum.reply': 'Reply',
    'forum.subforums': 'Sub-forums',
    'forum.searchPlaceholder': 'Find thread...',
    'auth.username': 'Username',
    'auth.password': 'Password',
    'auth.email': 'Email',
    'auth.phone': 'Phone Number',
    'auth.confirmPassword': 'Confirm Password',
    'auth.loginTitle': 'Sign In',
    'auth.registerTitle': 'Create Account',
    'auth.forgotPassword': 'You forget password?',
    'auth.rememberMe': 'Remember me',
    'auth.noAccount': 'You no get account?',
    'auth.haveAccount': 'You get account already?',
    'auth.signUp': 'Sign Up',
    'auth.signIn': 'Sign In',
    'auth.country': 'Country',
    'auth.language': 'Language',
    'auth.selectCountry': 'Choose your country',
    'auth.selectLanguage': 'Choose your language',
    'profile.motto': 'Motto',
    'profile.posts': 'Posts',
    'profile.comments': 'Comments',
    'profile.joined': 'When you join',
    'profile.editProfile': 'Edit Profile',
    'profile.sendMessage': 'Send Message',
    'profile.activity': 'Activity',
    'profile.updates': 'Updates',
    'profile.settings': 'Settings',
    'messages.inbox': 'Inbox',
    'messages.sent': 'Sent',
    'messages.compose': 'Compose',
    'messages.subject': 'Subject',
    'messages.content': 'Message',
    'messages.send': 'Send',
    'messages.noMessages': 'No messages',
    'blog.latest': 'Latest Articles',
    'blog.readMore': 'Read More',
    'blog.author': 'Author',
    'blog.published': 'Published',
    'blog.related': 'Related Articles',
    'blog.minRead': 'min read',
    'blog.backToBlog': 'Back to Blog',
    'game.play': 'Play',
    'game.score': 'Score',
    'game.highScore': 'High Score',
    'game.leaderboard': 'Leaderboard',
    'game.start': 'Start Game',
    'game.gameOver': 'Game Over',
    'game.restart': 'Play Again',
    'seo.siteTitle': 'Watch Trading Forum',
    'seo.siteDescription': 'The best place for watch traders and collectors for all over the world',
    'seo.forumTitle': 'Watch Trading Forum',
    'seo.blogTitle': 'Watch Trading Blog',
  },
  // Marathi
  mr: {
    'nav.home': 'मुख्यपृष्ठ',
    'nav.forum': 'फोरम',
    'nav.members': 'सदस्य',
    'nav.messages': 'संदेश',
    'nav.blog': 'ब्लॉग',
    'nav.game': 'गेम',
    'nav.search': 'शोध',
    'nav.login': 'लॉग इन',
    'nav.register': 'नोंदणी',
    'nav.logout': 'लॉग आउट',
    'nav.profile': 'प्रोफाइल',
    'nav.settings': 'सेटिंग्स',
    'nav.admin': 'ॲडमिन',
    'common.loading': 'लोड होत आहे...',
    'common.error': 'त्रुटी',
    'common.success': 'यशस्वी',
    'common.cancel': 'रद्द करा',
    'common.save': 'जतन करा',
    'common.delete': 'हटवा',
    'common.edit': 'संपादित करा',
    'common.create': 'तयार करा',
    'common.search': 'शोधा',
    'common.filter': 'फिल्टर',
    'common.sort': 'क्रमवारी',
    'common.newest': 'नवीनतम',
    'common.oldest': 'जुने',
    'common.hot': 'लोकप्रिय',
    'common.all': 'सर्व',
    'forum.threads': 'थ्रेड्स',
    'forum.posts': 'पोस्ट्स',
    'forum.comments': 'टिप्पण्या',
    'forum.replies': 'प्रतिसाद',
    'forum.views': 'व्ह्यूज',
    'forum.lastPost': 'शेवटची पोस्ट',
    'forum.noThreads': 'अद्याप कोणतेही थ्रेड नाहीत',
    'forum.createThread': 'थ्रेड तयार करा',
    'forum.reply': 'प्रतिसाद द्या',
    'forum.subforums': 'उप-फोरम्स',
    'forum.searchPlaceholder': 'थ्रेड शोधा...',
    'auth.username': 'वापरकर्तानाव',
    'auth.password': 'पासवर्ड',
    'auth.email': 'ईमेल',
    'auth.phone': 'फोन नंबर',
    'auth.confirmPassword': 'पासवर्डची पुष्टी करा',
    'auth.loginTitle': 'साइन इन',
    'auth.registerTitle': 'खाते तयार करा',
    'auth.forgotPassword': 'पासवर्ड विसरलात?',
    'auth.rememberMe': 'मला लक्षात ठेवा',
    'auth.noAccount': 'खाते नाही?',
    'auth.haveAccount': 'आधीपासूनच खाते आहे?',
    'auth.signUp': 'साइन अप',
    'auth.signIn': 'साइन इन',
    'auth.country': 'देश',
    'auth.language': 'भाषा',
    'auth.selectCountry': 'तुमचा देश निवडा',
    'auth.selectLanguage': 'तुमची भाषा निवडा',
    'profile.motto': 'मोटो',
    'profile.posts': 'पोस्ट्स',
    'profile.comments': 'टिप्पण्या',
    'profile.joined': 'सामील झाले',
    'profile.editProfile': 'प्रोफाइल संपादित करा',
    'profile.sendMessage': 'संदेश पाठवा',
    'profile.activity': 'क्रियाकलाप',
    'profile.updates': 'अपडेट्स',
    'profile.settings': 'सेटिंग्स',
    'messages.inbox': 'इनबॉक्स',
    'messages.sent': 'पाठवलेले',
    'messages.compose': 'लिहा',
    'messages.subject': 'विषय',
    'messages.content': 'संदेश',
    'messages.send': 'पाठवा',
    'messages.noMessages': 'कोणतेही संदेश नाहीत',
    'blog.latest': 'नवीनतम लेख',
    'blog.readMore': 'अधिक वाचा',
    'blog.author': 'लेखक',
    'blog.published': 'प्रकाशित',
    'blog.related': 'संबंधित लेख',
    'blog.minRead': 'मिनिटे वाचन',
    'blog.backToBlog': 'ब्लॉगवर परत जा',
    'game.play': 'खेळा',
    'game.score': 'स्कोर',
    'game.highScore': 'उच्च स्कोर',
    'game.leaderboard': 'लीडरबोर्ड',
    'game.start': 'सुरू करा',
    'game.gameOver': 'गेम संपले',
    'game.restart': 'पुन्हा खेळा',
    'seo.siteTitle': 'घड्याळ व्यापार फोरम',
    'seo.siteDescription': 'जगभरातील घड्याळ व्यापारी आणि संग्राहकांसाठी अग्रगण्य समुदाय',
    'seo.forumTitle': 'घड्याळ व्यापार फोरम',
    'seo.blogTitle': 'घड्याळ व्यापार ब्लॉग',
  },
  // Dutch
  nl: {
    'nav.home': 'Home',
    'nav.forum': 'Forum',
    'nav.members': 'Leden',
    'nav.messages': 'Berichten',
    'nav.blog': 'Blog',
    'nav.game': 'Spel',
    'nav.search': 'Zoeken',
    'nav.login': 'Inloggen',
    'nav.register': 'Registreren',
    'nav.logout': 'Uitloggen',
    'nav.profile': 'Profiel',
    'nav.settings': 'Instellingen',
    'nav.admin': 'Beheer',
    'common.loading': 'Laden...',
    'common.error': 'Fout',
    'common.success': 'Succes',
    'common.cancel': 'Annuleren',
    'common.save': 'Opslaan',
    'common.delete': 'Verwijderen',
    'common.edit': 'Bewerken',
    'common.create': 'Maken',
    'common.search': 'Zoeken',
    'common.filter': 'Filteren',
    'common.sort': 'Sorteren',
    'common.newest': 'Nieuwste',
    'common.oldest': 'Oudste',
    'common.hot': 'Populair',
    'common.all': 'Alles',
    'forum.threads': 'Topics',
    'forum.posts': 'Berichten',
    'forum.comments': 'Reacties',
    'forum.replies': 'Antwoorden',
    'forum.views': 'Weergaven',
    'forum.lastPost': 'Laatste bericht',
    'forum.noThreads': 'Nog geen topics',
    'forum.createThread': 'Topic maken',
    'forum.reply': 'Reageren',
    'forum.subforums': 'Subforums',
    'forum.searchPlaceholder': 'Topics zoeken...',
    'auth.username': 'Gebruikersnaam',
    'auth.password': 'Wachtwoord',
    'auth.email': 'E-mail',
    'auth.phone': 'Telefoonnummer',
    'auth.confirmPassword': 'Wachtwoord bevestigen',
    'auth.loginTitle': 'Inloggen',
    'auth.registerTitle': 'Account aanmaken',
    'auth.forgotPassword': 'Wachtwoord vergeten?',
    'auth.rememberMe': 'Onthoud mij',
    'auth.noAccount': 'Geen account?',
    'auth.haveAccount': 'Al een account?',
    'auth.signUp': 'Registreren',
    'auth.signIn': 'Inloggen',
    'auth.country': 'Land',
    'auth.language': 'Taal',
    'auth.selectCountry': 'Selecteer je land',
    'auth.selectLanguage': 'Selecteer je taal',
    'profile.motto': 'Motto',
    'profile.posts': 'Berichten',
    'profile.comments': 'Reacties',
    'profile.joined': 'Lid sinds',
    'profile.editProfile': 'Profiel bewerken',
    'profile.sendMessage': 'Bericht versturen',
    'profile.activity': 'Activiteit',
    'profile.updates': 'Updates',
    'profile.settings': 'Instellingen',
    'messages.inbox': 'Postvak IN',
    'messages.sent': 'Verzonden',
    'messages.compose': 'Opstellen',
    'messages.subject': 'Onderwerp',
    'messages.content': 'Bericht',
    'messages.send': 'Versturen',
    'messages.noMessages': 'Geen berichten',
    'blog.latest': 'Nieuwste artikelen',
    'blog.readMore': 'Lees meer',
    'blog.author': 'Auteur',
    'blog.published': 'Gepubliceerd',
    'blog.related': 'Gerelateerde artikelen',
    'blog.minRead': 'min leestijd',
    'blog.backToBlog': 'Terug naar blog',
    'game.play': 'Spelen',
    'game.score': 'Score',
    'game.highScore': 'Highscore',
    'game.leaderboard': 'Ranglijst',
    'game.start': 'Starten',
    'game.gameOver': 'Game Over',
    'game.restart': 'Opnieuw spelen',
    'seo.siteTitle': 'Horloge Handel Forum',
    'seo.siteDescription': 'De toonaangevende community voor horlogehandelaren en verzamelaars wereldwijd',
    'seo.forumTitle': 'Horloge Handel Forum',
    'seo.blogTitle': 'Horloge Handel Blog',
  },
};

// ============================================
// LANGUAGE STORE INTERFACE
// ============================================
interface LanguageState {
  currentLanguage: LanguageCode;
  setLanguage: (code: LanguageCode) => void;
  t: (key: TranslationKey) => string;
  getCurrentLanguage: () => Language;
}

// ============================================
// LANGUAGE STORE
// ============================================
export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      currentLanguage: 'en',
      
      setLanguage: (code) => {
        set({ currentLanguage: code });
        // Update document direction for RTL languages
        const lang = getLanguageByCode(code);
        document.documentElement.dir = lang.dir;
        document.documentElement.lang = code;
      },
      
      t: (key) => {
        const { currentLanguage } = get();
        const langTranslations = translations[currentLanguage];
        return langTranslations?.[key] || translations.en[key] || key;
      },
      
      getCurrentLanguage: () => {
        return getLanguageByCode(get().currentLanguage);
      },
    }),
    {
      name: 'watch-forum-language',
      partialize: (state) => ({ currentLanguage: state.currentLanguage }),
    }
  )
);
